// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"FitnessSpace/provider"
)

// Injectors from wire.go:

func InitDB() *provider.Database {
	database := provider.NewDB()
	return database
}
